spring:
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
  cache:
    type: redis

  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC
  kafka:
    bootstrap-servers: localhost:19092, localhost:19093, localhost:19094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: application
    password: application

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.loader.Loader: trace

---
spring.config.activate.on-profile: test

# Testcontainers JDBC URL
spring:
  datasource:
    url: jdbc:tc:mysql:8.0:///hhplus?TC_INITSCRIPT=file:src/test/resources/init.sql
    username: application
    password: application
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.hibernate.orm.jdbc.bind: off